import type { Config } from 'tailwindcss'

export default {
  darkMode: 'class',
  content: [
    './components/**/*.{js,vue,ts}',
    './layouts/**/*.vue',
    './pages/**/*.vue',
    './plugins/**/*.{js,ts}',
    './app.vue',
    './app/**/*.vue',
  ],
  theme: {
    extend: {
      colors: {
        tertiary: '#b70438',
        'on-secondary': '#ffffff',
        'surface-bright': '#f8f9ff',
        'tertiary-fixed': '#ffdadb',
        'surface-container-low': '#eff4ff',
        'on-secondary-container': '#5c647a',
        'surface-container-lowest': '#ffffff',
        'on-surface-variant': '#5c3f40',
        'inverse-surface': '#213145',
        secondary: '#565e74',
        'on-secondary-fixed': '#131b2e',
        'surface-container-highest': '#d3e4fe',
        'surface-variant': '#d3e4fe',
        'on-tertiary-fixed': '#40000d',
        'on-error': '#ffffff',
        background: '#f8f9ff',
        'surface-tint': '#be0037',
        'surface-dim': '#cbdbf5',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#db2b4e',
        'primary-fixed': '#ffdada',
        'on-secondary-fixed-variant': '#3f465c',
        surface: '#f8f9ff',
        'on-primary-fixed-variant': '#920028',
        'on-primary-container': '#fffaf9',
        'primary-fixed-dim': '#ffb3b6',
        'surface-container-high': '#dce9ff',
        'inverse-primary': '#ffb3b6',
        'primary-container': '#e11d48',
        'surface-container': '#e5eeff',
        'on-tertiary-container': '#fffaf9',
        'on-primary-fixed': '#40000c',
        'on-surface': '#0b1c30',
        'error-container': '#ffdad6',
        'on-background': '#0b1c30',
        'outline-variant': '#e5bdbe',
        'secondary-fixed-dim': '#bec6e0',
        'inverse-on-surface': '#eaf1ff',
        outline: '#906f70',
        error: '#ba1a1a',
        'tertiary-fixed-dim': '#ffb2b7',
        primary: '#b80035',
        'on-primary': '#ffffff',
        'secondary-fixed': '#dae2fd',
        'on-error-container': '#93000a',
        'on-tertiary-fixed-variant': '#92002a',
        'secondary-container': '#dae2fd',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        'space-2xl': '3rem',
        'space-md': '1rem',
        'space-4xl': '6rem',
        'gutter-mobile': '1rem',
        'space-xs': '0.5rem',
        'space-sm': '0.75rem',
        'space-3xl': '4.5rem',
        'gutter-desktop': '1.5rem',
        'space-lg': '1.5rem',
        'space-xl': '2rem',
        'max-width-editorial': '720px',
        'max-width-content': '1140px',
        'space-2xs': '0.25rem',
      },
      fontFamily: {
        'body-md': ['Geist', 'sans-serif'],
        'label-md': ['Geist', 'sans-serif'],
        display: ['Geist', 'sans-serif'],
        'body-lg': ['Geist', 'sans-serif'],
        'headline-xl-mobile': ['Geist', 'sans-serif'],
        'code-inline': ['JetBrains Mono', 'monospace'],
        'body-sm': ['Geist', 'sans-serif'],
        'headline-sm': ['Geist', 'sans-serif'],
        'headline-lg': ['Geist', 'sans-serif'],
        'label-mono': ['JetBrains Mono', 'monospace'],
        'display-mobile': ['Geist', 'sans-serif'],
        'headline-xl': ['Geist', 'sans-serif'],
        'code-block': ['JetBrains Mono', 'monospace'],
        'headline-md': ['Geist', 'sans-serif'],
      },
      fontSize: {
        'body-md': [
          '15px',
          {
            lineHeight: '24px',
            letterSpacing: '-0.005em',
            fontWeight: '400',
          },
        ],
        'label-md': [
          '13px',
          { lineHeight: '16px', letterSpacing: '0em', fontWeight: '500' },
        ],
        display: [
          '56px',
          {
            lineHeight: '64px',
            letterSpacing: '-0.04em',
            fontWeight: '600',
          },
        ],
        'body-lg': [
          '18px',
          {
            lineHeight: '28px',
            letterSpacing: '-0.01em',
            fontWeight: '400',
          },
        ],
        'headline-xl-mobile': [
          '28px',
          {
            lineHeight: '36px',
            letterSpacing: '-0.02em',
            fontWeight: '600',
          },
        ],
        'code-inline': [
          '13px',
          {
            lineHeight: '20px',
            letterSpacing: '-0.01em',
            fontWeight: '400',
          },
        ],
        'body-sm': [
          '13px',
          { lineHeight: '20px', letterSpacing: '0em', fontWeight: '400' },
        ],
        'headline-sm': [
          '16px',
          {
            lineHeight: '24px',
            letterSpacing: '-0.01em',
            fontWeight: '500',
          },
        ],
        'headline-lg': [
          '28px',
          {
            lineHeight: '36px',
            letterSpacing: '-0.02em',
            fontWeight: '600',
          },
        ],
        'label-mono': [
          '11px',
          {
            lineHeight: '14px',
            letterSpacing: '0.04em',
            fontWeight: '500',
          },
        ],
        'display-mobile': [
          '36px',
          {
            lineHeight: '44px',
            letterSpacing: '-0.03em',
            fontWeight: '600',
          },
        ],
        'headline-xl': [
          '40px',
          {
            lineHeight: '48px',
            letterSpacing: '-0.03em',
            fontWeight: '600',
          },
        ],
        'code-block': [
          '12px',
          { lineHeight: '18px', letterSpacing: '0em', fontWeight: '400' },
        ],
        'headline-md': [
          '20px',
          {
            lineHeight: '28px',
            letterSpacing: '-0.015em',
            fontWeight: '500',
          },
        ],
      },
      keyframes: {
        fadeInUp: {
          '0%': { opacity: '0', transform: 'translateY(16px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        slideInRight: {
          '0%': { opacity: '0', transform: 'translateX(20px)' },
          '100%': { opacity: '1', transform: 'translateX(0)' },
        },
        toastIn: {
          '0%': { opacity: '0', transform: 'translateY(10px) scale(0.95)' },
          '100%': { opacity: '1', transform: 'translateY(0) scale(1)' },
        },
      },
      animation: {
        'fade-in-up': 'fadeInUp 0.5s ease-out forwards',
        'slide-in-right': 'slideInRight 0.4s ease-out forwards',
        'toast-in': 'toastIn 0.25s ease-out forwards',
      },
    },
  },
  plugins: [],
} satisfies Config
